-- megafunction wizard: %Partial Reconfiguration v16.0%
-- GENERATION: XML
-- prip.vhd

-- Generated using ACDS version 16.0 211

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity prip is
	port (
		clk            : in  std_logic                     := '0';             --            clk.clk
		nreset         : in  std_logic                     := '0';             --         nreset.reset_n
		pr_start       : in  std_logic                     := '0';             --       pr_start.pr_start
		double_pr      : in  std_logic                     := '0';             --      double_pr.double_pr
		freeze         : out std_logic;                                        --         freeze.freeze
		status         : out std_logic_vector(2 downto 0);                     --         status.status
		pr_ready_pin   : in  std_logic                     := '0';             --   pr_ready_pin.pr_ready_pin
		pr_done_pin    : in  std_logic                     := '0';             --    pr_done_pin.pr_done_pin
		pr_error_pin   : in  std_logic                     := '0';             --   pr_error_pin.pr_error_pin
		crc_error_pin  : in  std_logic                     := '0';             --  crc_error_pin.crc_error_pin
		pr_request_pin : out std_logic;                                        -- pr_request_pin.pr_request_pin
		pr_clk_pin     : out std_logic;                                        --     pr_clk_pin.pr_clk_pin
		pr_data_pin    : out std_logic_vector(15 downto 0);                    --    pr_data_pin.pr_data_pin
		data           : in  std_logic_vector(15 downto 0) := (others => '0'); --      avst_sink.data
		data_valid     : in  std_logic                     := '0';             --               .valid
		data_ready     : out std_logic                                         --               .ready
	);
end entity prip;

architecture rtl of prip is
	component alt_pr is
		generic (
			PR_INTERNAL_HOST              : boolean := true;
			ENABLE_JTAG                   : boolean := true;
			ENABLE_AVMM_SLAVE             : boolean := false;
			ENABLE_INTERRUPT              : boolean := false;
			ENABLE_PRPOF_ID_CHECK         : boolean := false;
			EXT_HOST_PRPOF_ID             : integer := 0;
			EXT_HOST_TARGET_DEVICE_FAMILY : string  := "Stratix V";
			DATA_WIDTH_INDEX              : integer := 16;
			CB_DATA_WIDTH                 : integer := 16;
			ENABLE_DATA_PACKING           : boolean := true;
			CDRATIO                       : integer := 1;
			EDCRC_OSC_DIVIDER             : integer := 1;
			ENABLE_ENHANCED_DECOMPRESSION : boolean := false;
			INSTANTIATE_PR_BLOCK          : boolean := true;
			INSTANTIATE_CRC_BLOCK         : boolean := true;
			DEVICE_FAMILY                 : string  := ""
		);
		port (
			clk                    : in  std_logic                     := 'X';             -- clk
			nreset                 : in  std_logic                     := 'X';             -- reset_n
			pr_start               : in  std_logic                     := 'X';             -- pr_start
			double_pr              : in  std_logic                     := 'X';             -- double_pr
			freeze                 : out std_logic;                                        -- freeze
			status                 : out std_logic_vector(2 downto 0);                     -- status
			pr_ready_pin           : in  std_logic                     := 'X';             -- pr_ready_pin
			pr_done_pin            : in  std_logic                     := 'X';             -- pr_done_pin
			pr_error_pin           : in  std_logic                     := 'X';             -- pr_error_pin
			crc_error_pin          : in  std_logic                     := 'X';             -- crc_error_pin
			pr_request_pin         : out std_logic;                                        -- pr_request_pin
			pr_clk_pin             : out std_logic;                                        -- pr_clk_pin
			pr_data_pin            : out std_logic_vector(15 downto 0);                    -- pr_data_pin
			data                   : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			data_valid             : in  std_logic                     := 'X';             -- valid
			data_ready             : out std_logic;                                        -- ready
			avmm_slave_address     : in  std_logic                     := 'X';             -- address
			avmm_slave_read        : in  std_logic                     := 'X';             -- read
			avmm_slave_writedata   : in  std_logic_vector(15 downto 0) := (others => 'X'); -- writedata
			avmm_slave_write       : in  std_logic                     := 'X';             -- write
			avmm_slave_readdata    : out std_logic_vector(15 downto 0);                    -- readdata
			avmm_slave_waitrequest : out std_logic;                                        -- waitrequest
			irq                    : out std_logic                                         -- irq
		);
	end component alt_pr;

begin

	prip_inst : component alt_pr
		generic map (
			PR_INTERNAL_HOST              => false,
			ENABLE_JTAG                   => true,
			ENABLE_AVMM_SLAVE             => false,
			ENABLE_INTERRUPT              => false,
			ENABLE_PRPOF_ID_CHECK         => false,
			EXT_HOST_PRPOF_ID             => 0,
			EXT_HOST_TARGET_DEVICE_FAMILY => "Stratix V",
			DATA_WIDTH_INDEX              => 16,
			CB_DATA_WIDTH                 => 16,
			ENABLE_DATA_PACKING           => true,
			CDRATIO                       => 1,
			EDCRC_OSC_DIVIDER             => 1,
			ENABLE_ENHANCED_DECOMPRESSION => false,
			INSTANTIATE_PR_BLOCK          => true,
			INSTANTIATE_CRC_BLOCK         => true,
			DEVICE_FAMILY                 => "Cyclone V"
		)
		port map (
			clk                    => clk,                --            clk.clk
			nreset                 => nreset,             --         nreset.reset_n
			pr_start               => pr_start,           --       pr_start.pr_start
			double_pr              => double_pr,          --      double_pr.double_pr
			freeze                 => freeze,             --         freeze.freeze
			status                 => status,             --         status.status
			pr_ready_pin           => pr_ready_pin,       --   pr_ready_pin.pr_ready_pin
			pr_done_pin            => pr_done_pin,        --    pr_done_pin.pr_done_pin
			pr_error_pin           => pr_error_pin,       --   pr_error_pin.pr_error_pin
			crc_error_pin          => crc_error_pin,      --  crc_error_pin.crc_error_pin
			pr_request_pin         => pr_request_pin,     -- pr_request_pin.pr_request_pin
			pr_clk_pin             => pr_clk_pin,         --     pr_clk_pin.pr_clk_pin
			pr_data_pin            => pr_data_pin,        --    pr_data_pin.pr_data_pin
			data                   => data,               --      avst_sink.data
			data_valid             => data_valid,         --               .valid
			data_ready             => data_ready,         --               .ready
			avmm_slave_address     => '0',                --    (terminated)
			avmm_slave_read        => '0',                --    (terminated)
			avmm_slave_writedata   => "0000000000000000", --    (terminated)
			avmm_slave_write       => '0',                --    (terminated)
			avmm_slave_readdata    => open,               --    (terminated)
			avmm_slave_waitrequest => open,               --    (terminated)
			irq                    => open                --    (terminated)
		);

end architecture rtl; -- of prip
-- Retrieval info: <?xml version="1.0"?>
--<!--
--	Generated by Altera MegaWizard Launcher Utility version 1.0
--	************************************************************
--	THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--	************************************************************
--	Copyright (C) 1991-2026 Altera Corporation
--	Any megafunction design, and related net list (encrypted or decrypted),
--	support information, device programming or simulation file, and any other
--	associated documentation or information provided by Altera or a partner
--	under Altera's Megafunction Partnership Program may be used only to
--	program PLD devices (but not masked PLD devices) from Altera.  Any other
--	use of such megafunction design, net list, support information, device
--	programming or simulation file, or any other related documentation or
--	information is prohibited for any other purpose, including, but not
--	limited to modification, reverse engineering, de-compiling, or use with
--	any other silicon devices, unless such use is explicitly licensed under
--	a separate agreement with Altera or a megafunction partner.  Title to
--	the intellectual property, including patents, copyrights, trademarks,
--	trade secrets, or maskworks, embodied in any such megafunction design,
--	net list, support information, device programming or simulation file, or
--	any other related documentation or information provided by Altera or a
--	megafunction partner, remains with Altera, the megafunction partner, or
--	their respective licensors.  No other licenses, including any licenses
--	needed under any third party's intellectual property, are provided herein.
---->
-- Retrieval info: <instance entity-name="alt_pr" version="16.0" >
-- Retrieval info: 	<generic name="PR_INTERNAL_HOST" value="false" />
-- Retrieval info: 	<generic name="ENABLE_JTAG" value="true" />
-- Retrieval info: 	<generic name="ENABLE_AVMM_SLAVE" value="false" />
-- Retrieval info: 	<generic name="ENABLE_INTERRUPT" value="false" />
-- Retrieval info: 	<generic name="ENABLE_PRPOF_ID_CHECK_UI" value="false" />
-- Retrieval info: 	<generic name="EXT_HOST_PRPOF_ID" value="0" />
-- Retrieval info: 	<generic name="EXT_HOST_TARGET_DEVICE_FAMILY" value="Stratix V" />
-- Retrieval info: 	<generic name="DATA_WIDTH_INDEX" value="16" />
-- Retrieval info: 	<generic name="CDRATIO" value="1" />
-- Retrieval info: 	<generic name="EDCRC_OSC_DIVIDER" value="1" />
-- Retrieval info: 	<generic name="ENABLE_ENHANCED_DECOMPRESSION" value="false" />
-- Retrieval info: 	<generic name="INSTANTIATE_PR_BLOCK" value="true" />
-- Retrieval info: 	<generic name="INSTANTIATE_CRC_BLOCK" value="true" />
-- Retrieval info: 	<generic name="DEVICE_FAMILY" value="Cyclone V" />
-- Retrieval info: </instance>
-- IPFS_FILES : prip.vho
-- RELATED_FILES: prip.vhd, alt_pr.v, alt_pr_bitstream_host.v, alt_pr_bitstream_controller_v1.v, alt_pr_bitstream_controller_v2.v, alt_pr_cb_host.v, alt_pr_cb_interface.v, alt_pr_cb_controller_v1.v, alt_pr_cb_controller_v2.v, alt_pr_mux.sv, alt_pr_jtag_interface.v, alt_pr_width_adapter.sv, alt_pr_bitstream_compatibility_checker_int_host.v, alt_pr_bitstream_compatibility_checker_ext_host.v, alt_pr_down_converter.sv, alt_pr_fifo.sv, alt_pr_up_converter.sv, alt_pr_bitstream_decoder.sv, alt_pr_enhanced_compression_magic_words_decoder_and_suppressor.sv, alt_pr_enhanced_decompressor.sv, alt_pr_magic_fifo.sv, alt_pr_data.sv
